'use client';

import { useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Instagram, Linkedin, MapPin, Phone, Truck } from 'lucide-react';
import Header from '@/components/Header';
import TruckSpecCard from '@/components/TruckSpecCard';
import QuoteForm from '@/components/QuoteForm';
import { company, copy, imageDirections, Language, locations, services, whyZoink } from '@/data/site';

const photos = {
  project: 'https://images.unsplash.com/photo-1590644365607-1c5a3c04a5a1?auto=format&fit=crop&w=1200&q=85',
  mountains: 'https://images.unsplash.com/photo-1516939884455-1445c8652f83?auto=format&fit=crop&w=1400&q=85',
  material: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1200&q=85',
  close: 'https://images.unsplash.com/photo-1531835551805-16d864c8d311?auto=format&fit=crop&w=1200&q=85'
};

export default function Home() {
  const [language, setLanguage] = useState<Language>('en');
  const t = copy[language];

  return <main>
    <Header language={language} setLanguage={setLanguage} />

    <section id="home" className="hero-grid grain relative min-h-[730px] overflow-hidden bg-[#16191b] text-white">
      <div className="section-wrap relative flex min-h-[730px] flex-col justify-center pb-14 pt-32">
        <div className="max-w-3xl fade-up"><div className="mb-6 flex items-center gap-3"><span className="blue-rule" /><span className="eyebrow text-white/70">{t.heroEyebrow}</span></div><h1 className="display max-w-3xl whitespace-pre-line text-[clamp(66px,10vw,148px)] leading-[.82]">{t.heroTitle}</h1><p className="mt-8 max-w-md text-base leading-7 text-white/72 md:text-lg">{t.heroBody}</p><div className="mt-9 flex flex-wrap gap-3"><a className="primary-link flex items-center gap-4" href="#contact">{t.requestQuote}<ArrowUpRight size={16} /></a><a className="outline-link flex items-center gap-3" href="#fleet">{t.exploreFleet}<ArrowDownRight size={15} /></a></div></div>
        <div className="absolute bottom-7 right-0 hidden items-end gap-5 md:flex"><div className="hero-vertical eyebrow text-white/45">BUILT FOR THE JOB / MOVEMOS EL SALVADOR / ZOINK</div><div className="h-20 w-px bg-white/25" /></div>
        <div className="absolute bottom-0 left-0 right-0"><div className="ticker"><span>Dump trucks</span><i>✳</i><span>Material hauling</span><i>✳</i><span>Construction support</span><i>✳</i><span>USA <b className="text-white">→</b> EL SALVADOR</span><i>✳</i><span>Dump trucks</span><i>✳</i><span>Material hauling</span></div></div>
      </div>
    </section>

    <section id="fleet" className="bg-[var(--paper)] py-24 md:py-32"><div className="section-wrap"><div className="mb-12 flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="eyebrow text-[var(--blue)]">{t.fleetKicker}</p><h2 className="display mt-4 whitespace-pre-line text-[clamp(58px,8vw,112px)] leading-[.82]">{t.fleetTitle}</h2></div><div className="max-w-xs md:pb-2"><p className="text-sm leading-6 text-[#716e67]">{t.fleetBody}</p><p className="mt-4 text-[10px] font-bold uppercase tracking-widest text-[#a56820]">{t.conceptLabel}</p></div></div><TruckSpecCard language={language} /></div></section>

    <section id="services" className="bg-[var(--charcoal)] py-24 text-white md:py-32"><div className="section-wrap"><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><div className="md:sticky md:top-24 md:h-fit"><p className="eyebrow text-[var(--blue-bright)]">{t.servicesKicker}</p><h2 className="display mt-4 whitespace-pre-line text-[clamp(58px,7vw,100px)] leading-[.82]">{t.servicesTitle}</h2><p className="mt-7 max-w-xs text-sm leading-6 text-white/55">{t.servicesBody}</p><div className="mt-10 flex items-center gap-3 text-[10px] font-bold uppercase tracking-widest text-white/45"><span className="h-px w-8 bg-[var(--blue-bright)]" /> scope to be confirmed</div></div><div className="grid gap-x-10 md:grid-cols-2">{services.map(([number, title, body]) => <div className="service-card" key={number}><div className="flex items-start justify-between gap-4"><span className="mono text-xs text-[var(--blue-bright)]">{number}</span><ArrowUpRight size={16} className="text-white/35" /></div><h3 className="mt-9 text-lg font-bold tracking-[-.02em]">{title}</h3><p className="mt-2 max-w-[210px] text-xs leading-5 text-white/45">{body}</p></div>)}</div></div></div></section>

    <section id="el-salvador" className="grain relative overflow-hidden bg-[#d7e0e2] py-24 md:py-32"><div className="section-wrap relative"><div className="grid items-center gap-12 md:grid-cols-[1fr_1.2fr]"><div><p className="eyebrow text-[var(--blue)]">{t.coverageKicker}</p><h2 className="display mt-4 whitespace-pre-line text-[clamp(58px,7vw,100px)] leading-[.82]">{t.coverageTitle}</h2><p className="mt-7 max-w-sm text-sm leading-6 text-[#4d5b5f]">{t.coverageBody}</p><div className="mt-9 flex items-center gap-3 text-[10px] font-bold uppercase tracking-widest text-[#667276]"><MapPin size={15} className="text-[var(--blue)]" /> coverage planning view</div></div><div className="relative min-h-[390px] overflow-hidden bg-[#bfd1d7]"><img src={photos.mountains} alt="Mountain landscape representing El Salvador" className="image-cover opacity-35 grayscale" /><div className="absolute inset-0 bg-[linear-gradient(135deg,rgba(45,114,184,.15),rgba(255,255,255,.1))]" /><div className="absolute left-1/2 top-1/2 h-[230px] w-[460px] max-w-[82%] -translate-x-1/2 -translate-y-1/2 rotate-[-8deg] bg-[var(--blue)] opacity-90 shadow-2xl map-shape" /><div className="absolute left-[44%] top-[38%] z-10 flex items-center gap-2"><span className="h-3 w-3 rounded-full border-2 border-white bg-[var(--blue-bright)] shadow-[0_0_0_5px_rgba(89,169,233,.25)]" /><span className="text-[9px] font-bold uppercase tracking-widest text-white">San Salvador</span></div><div className="absolute bottom-[30%] right-[24%] z-10 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-white" /><span className="text-[9px] font-bold uppercase tracking-widest text-white/90">San Miguel</span></div><div className="absolute left-[16%] top-[27%] z-10 text-[9px] font-bold uppercase tracking-widest text-white/70">Planning map</div></div></div><div className="mt-14 grid border-t border-[#aebfc2] sm:grid-cols-5">{locations.map(([name, status]) => <div className="border-b border-[#aebfc2] py-4 sm:border-b-0 sm:border-r sm:px-4 sm:first:pl-0" key={name}><p className="text-xs font-bold">{name}</p><p className="mt-1 text-[9px] uppercase tracking-widest text-[#667276]">{status}</p></div>)}</div></div></section>

    <section id="about" className="bg-[var(--ink)] py-24 text-white md:py-32"><div className="section-wrap"><div className="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow text-[var(--blue-bright)]">{t.expansionKicker}</p><h2 className="display mt-4 whitespace-pre-line text-[clamp(58px,8vw,112px)] leading-[.82]">{t.expansionTitle}</h2></div><p className="max-w-sm text-sm leading-6 text-white/55 md:pb-2">{t.expansionBody}</p></div><div className="grid min-h-[460px] md:grid-cols-2"><div className="relative overflow-hidden bg-[#25292b]"><img src={photos.close} alt="U.S. construction operations concept" className="image-cover grayscale opacity-65" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" /><div className="absolute bottom-7 left-7"><p className="eyebrow text-white/60">Origin</p><p className="display mt-2 text-4xl">United States</p></div></div><div className="relative overflow-hidden bg-[#879b9e]"><img src={photos.project} alt="El Salvador construction opportunity concept" className="image-cover opacity-65 grayscale-[.35]" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" /><div className="absolute bottom-7 left-7"><p className="eyebrow text-white/60">Opportunity</p><p className="display mt-2 text-4xl">El Salvador</p></div></div><div className="absolute left-1/2 mt-[210px] -translate-x-1/2 -translate-y-1/2 bg-[var(--blue)] px-6 py-4 text-center text-white shadow-xl"><p className="mono text-[10px] tracking-[.18em]">USA <span className="text-white/55">→</span> SV</p><p className="display mt-1 text-2xl">The bridge</p></div></div></div></section>

    <section id="projects" className="bg-[var(--paper)] py-24 md:py-32"><div className="section-wrap"><div className="mb-12 flex items-end justify-between"><div><p className="eyebrow text-[var(--blue)]">Visual direction / 10 frames</p><h2 className="display mt-4 text-[clamp(54px,7vw,94px)] leading-[.82]">The work,<br />in view.</h2></div><p className="hidden max-w-[220px] text-right text-xs leading-5 text-[#77736b] md:block">A flexible image system for future company photography and project stories.</p></div><div className="grid auto-rows-[170px] grid-cols-2 gap-3 md:auto-rows-[210px] md:grid-cols-4"><div className="photo-card col-span-2 row-span-2"><img src={photos.project} alt={imageDirections[2][2]} className="image-cover grayscale-[.3]" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" /><div className="absolute bottom-5 left-5 text-white"><p className="eyebrow text-white/60">01 / Project story</p><h3 className="display mt-1 text-3xl">Site development</h3></div></div><div className="photo-card"><img src={photos.material} alt={imageDirections[3][2]} className="image-cover" /><div className="absolute bottom-3 left-3 text-[9px] font-bold uppercase tracking-widest text-white drop-shadow">02 / Aggregate</div></div><div className="photo-card bg-[var(--blue)] p-5 text-white"><Truck size={29} /><p className="eyebrow mt-8 text-white/60">03 / Intent</p><p className="mt-2 text-sm font-bold leading-5">Consistent ZOINK branding across every future frame.</p></div><div className="photo-card"><img src={photos.mountains} alt={imageDirections[6][2]} className="image-cover" /><div className="absolute bottom-3 left-3 text-[9px] font-bold uppercase tracking-widest text-white drop-shadow">04 / Landscape</div></div><div className="photo-card"><img src={photos.close} alt={imageDirections[8][2]} className="image-cover grayscale" /><div className="absolute bottom-3 left-3 text-[9px] font-bold uppercase tracking-widest text-white drop-shadow">05 / Detail</div></div></div><p className="mt-5 text-[10px] uppercase tracking-widest text-[#99958d]">All imagery shown is concept direction — replace with approved ZOINK photography.</p></div></section>

    <section className="bg-[#e1dfd7] py-24 md:py-32"><div className="section-wrap"><div className="mb-12 flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="eyebrow text-[var(--blue)]">{t.whyKicker}</p><h2 className="display mt-4 whitespace-pre-line text-[clamp(58px,8vw,112px)] leading-[.82]">{t.whyTitle}</h2></div><p className="max-w-xs text-sm leading-6 text-[#716e67] md:pb-2">The details that make a hauling partner feel ready for the job. Claims and standards to be documented as the operation takes shape.</p></div><div className="grid gap-x-10 border-t border-[#bcb8ae] md:grid-cols-2">{whyZoink.map(([number, title, body]) => <div className="flex gap-5 border-b border-[#bcb8ae] py-6" key={number}><span className="mono pt-1 text-xs text-[var(--blue)]">{number}</span><div><h3 className="font-bold">{title}</h3><p className="mt-2 max-w-sm text-sm leading-5 text-[#716e67]">{body}</p></div></div>)}</div></div></section>

    <section id="contact" className="bg-[var(--paper)] py-24 md:py-32"><div className="section-wrap"><div className="grid gap-12 md:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[var(--blue)]">{t.quoteKicker}</p><h2 className="display mt-4 whitespace-pre-line text-[clamp(58px,7vw,100px)] leading-[.82]">{t.quoteTitle}</h2><p className="mt-7 max-w-sm text-sm leading-6 text-[#716e67]">{t.quoteBody}</p><a href={`https://wa.me/${company.whatsapp.replace(/\D/g, '')}`} className="mt-8 flex w-fit items-center gap-3 border border-[#bcb8ae] px-5 py-4 text-[10px] font-bold uppercase tracking-[.13em] transition hover:border-[var(--blue)] hover:text-[var(--blue)]"><Phone size={15} /> {t.whatsapp}</a><div className="mt-12 border-t border-[#c9c4b9] pt-5"><p className="eyebrow text-[#77736b]">Contact details</p><p className="mono mt-3 text-xs text-[#77736b]">{company.phone}</p><p className="mono mt-2 text-xs text-[#77736b]">{company.email}</p></div></div><QuoteForm language={language} /></div></div></section>

    <footer className="bg-[var(--ink)] py-10 text-white"><div className="section-wrap"><div className="flex flex-col justify-between gap-8 border-b border-white/15 pb-9 md:flex-row md:items-end"><div><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center bg-[var(--blue)] text-[13px] font-black tracking-[-.08em]">ZK</span><span className="display text-[25px]">ZOINK</span></div><p className="mt-4 text-[10px] font-bold uppercase tracking-[.16em] text-white/45">{company.locationLine}</p></div><div className="grid grid-cols-2 gap-x-10 gap-y-3 text-[10px] font-bold uppercase tracking-[.13em] text-white/55 sm:grid-cols-4"><a href="#services" className="hover:text-white">Services</a><a href="#fleet" className="hover:text-white">Fleet</a><a href="#contact" className="hover:text-white">Contact</a><a href="#el-salvador" className="hover:text-white">Coverage</a></div><div className="flex gap-3"><a href="#" aria-label="Instagram" className="border border-white/20 p-2 text-white/70 hover:text-white"><Instagram size={15} /></a><a href="#" aria-label="LinkedIn" className="border border-white/20 p-2 text-white/70 hover:text-white"><Linkedin size={15} /></a></div></div><div className="flex flex-col justify-between gap-4 pt-5 text-[9px] uppercase tracking-[.15em] text-white/35 sm:flex-row"><span>© 2026 ZOINK / Concept site</span><span>Privacy &nbsp;&nbsp; Terms &nbsp;&nbsp; Site information to be confirmed</span></div></div></footer>
  </main>;
}
